apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv  # Nombre del PersistentVolume
  namespace: k8space
spec:
  capacity:
    storage: 1Gi  # Capacidad de almacenamiento
  accessModes:
    - ReadWriteOnce  # Modo de acceso
  hostPath:
    path: /mnt/data  # Directorio en el nodo donde se almacenarán los datos
